#Global configuration
spring.application.name=CoursesCrawler

#False for dev mod only
spring.thymeleaf.cache=false

 #Tomcat configuration
 server.port=9001
 
#Log level configuration
logging.level.root=INFO
  
# output to a file  // Injected in logback-spring.xml that add .log
logging.file.name=logs/${spring.application.name}
  
  
 #Mysql Config
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/courses
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cron
# Daily main crawl
fr.ses10doigts.crawler.monthlyTask=0 10 0 1 * *
fr.ses10doigts.crawler.dailyMorningTask=0 0 10 * * *
fr.ses10doigts.crawler.dailyEveningTask=0 0 22 * * *
fr.ses10doigts.crawler.schedulerChecker=20 * * * * ?


archive.root-path=/home/oklm/courses/archive
fr.ses10doigts.crawler.maxHop=1
fr.ses10doigts.crawler.seedsFile=seeds.txt
fr.ses10doigts.crawler.authorizedFile=authorized.txt
fr.ses10doigts.crawler.maxRetry=1
#HARD, MEDIUM_HARD, MEDIUM, SOFT, REALLY_SOFT
fr.ses10doigts.crawler.agressivity=MEDIUM_HARD
fr.ses10doigts.crawler.doCrawl=true
fr.ses10doigts.crawler.doRefacto=true
fr.ses10doigts.crawler.doExcel=true
fr.ses10doigts.crawler.doArchive=false

# Checks
fr.ses10doigts.crawler.checkTimeBefore=10

# Filters
fr.ses10doigts.crawler.filterMinPartants=9
fr.ses10doigts.crawler.filterMinPourcent=40.5
fr.ses10doigts.crawler.filterTypeCourse=plat
fr.ses10doigts.crawler.filterNbReunionMax=5
fr.ses10doigts.crawler.filterNbPartants=9,10,14,15,16
fr.ses10doigts.crawler.filterListAcceptedHippo=argentan,bordeaux-le bouscat,chantilly,cagnes,compi,craon,deauville,dax,la teste-de-buch,le lion-d,le mans,touquet,ligni,lyon-la soie,lyon-parilly,mont-de-marsan,nancy,parislongchamp,tarbes,vichy
fr.ses10doigts.crawler.filterListAuthorizedAges=3~*, 4-4, 4-6, 4-8, 4-10, 5~9

# Bet
fr.ses10doigts.crawler.puppeteerInitialBet=10
fr.ses10doigts.crawler.puppeteerMartingale=1,2,3


