#Global configuration
spring.application.name=CoursesCrawler

#False for dev mod only
spring.thymeleaf.cache=false

 #Tomcat configuration
 server.port=9001
 
#Log level configuration
logging.level.root=ERROR
logging.level.org.springframework.boot.web.embedded.tomcat=INFO
  
# output to a file  // Injected in logback-spring.xml that add .log
logging.file.name=logs/${spring.application.name}
  
  
 #Mysql Config
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/courses
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cron
# Daily main crawl
fr.ses10doigts.crawler.dailyMorningTask=0 0 10 * * *
fr.ses10doigts.crawler.dailyEveningTask=0 0 22 * * *
# Scheduler checker => Verify if there's a task to launch
fr.ses10doigts.crawler.schedulerChecker=20 * * * * ?

  
fr.ses10doigts.crawler.maxHop=1
fr.ses10doigts.crawler.seedsFile=seeds.txt
fr.ses10doigts.crawler.authorizedFile=authorized.txt
fr.ses10doigts.crawler.maxRetry=1
#HARD, MEDIUM_HARD, MEDIUM, SOFT, REALLY_SOFT
fr.ses10doigts.crawler.agressivity=MEDIUM_HARD
fr.ses10doigts.crawler.doCrawl=true
fr.ses10doigts.crawler.doRefacto=true

# Bet
fr.ses10doigts.crawler.puppeteerInitialBet=1

